### PR TITLE
Refactor Networks doc

### PR DESCRIPTION
**Pull request by catlook**
Partially closes issue #110

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/build-88acfe7342/docs/cloud-networks/v2/developer-guide/). :bow:

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/build-e83eb1c466/docs/cloud-networks/v2/developer-guide/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-80e155cfd3/docs/cloud-networks/v2/developer-guide/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-7cf87fc583/docs/cloud-networks/v2/developer-guide/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/build-f5d79a6483/docs/cloud-networks/v2/developer-guide/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/build-fc4b73533f/docs/cloud-networks/v2/developer-guide/).

**Comment by catlook** [comment]
related PRs: https://github.com/rackerlabs/docs-quickstart/pull/116
https://github.com/rackerlabs/nexus-control/pull/560

**Pull request merged**
