### PR TITLE
Fix link and warning issues.

### PR DESCRIPTION
**Pull request by catlook**
**Quality audit reminder**

Doc team: Use the quality checklist at http://goo.gl/forms/GaRzOmhzr5 to ensure that the 
content of the PR meets minimal writing and style requirements, and has received an 
appropriate subject matter expert (SME) review. Complete the checklist for significant
doc changes or additions that you submit or that are submitted by a non-doc staff contributor.

Closes issue #122 and issue #123

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/build-396e3263dc/docs/cloud-networks/v2/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-fc3e3a4e10/docs/cloud-networks/v2/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/build-366485d20e/docs/cloud-networks/v2/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/build-07c4c34cc3/docs/cloud-networks/v2/)

**Comment by cyrichardson** [comment]
LGTM - merging

**Pull request merged**
